FROM ubuntu:22.04
LABEL Maintainer="Sarayut (Nine) Winuthayanon, https://www.linkedin.com/in/winuthayanons/"

RUN apt update -y && \
    apt install -y wget tree default-jdk && \
    rm -rf /var/lib/apt/lists/*

RUN wget -qO- https://get.nextflow.io | bash \
  && mv nextflow /usr/local/bin \
  && chmod 755 /usr/local/bin/nextflow 

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
RUN bash ~/miniconda.sh -b -p /opt/miniconda
RUN rm -f ~/miniconda.sh
    
ENV PATH="/opt/miniconda/bin:${PATH}"
RUN conda update -n base conda -y

RUN pip install multiqc
RUN conda install -c bioconda fastqc trimmomatic -y